# Generated by Django 5.2.5 on 2025-08-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profild_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
