# Generated by Django 5.2.5 on 2025-08-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_profild_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Post_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
