# Generated by Django 5.2.5 on 2025-08-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profild_Image',
            new_name='profile_Image',
        ),
    ]
