# Generated by Django 5.2.5 on 2025-08-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_profild_image_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='User',
            new_name='user',
        ),
    ]
